framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: pitcrew

        # Configuration du cache
        app: cache.adapter.filesystem
        system: cache.adapter.system
        
        # Namespaced pools use the above "app" backend by default
        pools:
            # Cache pour les données de l'application
            app.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false
            
            # Cache pour Doctrine
            doctrine.system_cache_pool:
                adapter: cache.adapter.system
                default_lifetime: 86400
                public: false
            
            # Cache pour les résultats de requêtes Doctrine
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false
            
            # Cache pour les métadonnées Doctrine
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.system
                default_lifetime: 86400
                public: false

            # Cache pour les sessions
            session.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false

            # Cache pour les validations
            validator.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false

            # Cache pour les annotations
            annotations.cache_pool:
                adapter: cache.adapter.system
                default_lifetime: 86400
                public: false

            # Cache pour les routes
            router.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false

            # Cache pour les traductions
            translation.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false

            # Cache pour les profils
            profiler.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false

            # Cache pour les métriques
            metrics.cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 300
                public: false

# En production, on peut configurer des adaptateurs plus performants si disponibles
when@prod:
    framework:
        cache:
            app: cache.adapter.redis
            system: cache.adapter.redis
            default_redis_provider: redis://redis:6379
