framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        prefix_seed: pitcrew

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        #default_redis_provider: redis://localhost

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            # Cache pour les données de l'application
            app.cache:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false
                tags: true
            
            # Cache pour Doctrine
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400
                public: false
                tags: true
            
            # Cache pour les résultats de requêtes Doctrine
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 3600
                public: false
                tags: true
            
            # Cache pour les métadonnées Doctrine
            doctrine.metadata_cache_pool:
                adapter: cache.adapter.filesystem
                default_lifetime: 86400
                public: false
                tags: true
