twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - '@EasyAdmin/symfony-form-themes/bootstrap_5_layout.html.twig'
    paths:
        '%kernel.project_dir%/templates/admin': admin
        '%kernel.project_dir%/vendor/easycorp/easyadmin-bundle/templates': EasyAdmin

when@test:
    twig:
        strict_variables: true
