# version: '3.8' - Supprimé car obsolète

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
      - symfony-cache:/var/www/var/cache
      - symfony-logs:/var/www/var/log
      - node-modules:/var/www/node_modules
    environment:
      APP_ENV: dev
      APP_SECRET: "a7c8b9d0e1f2g3h4i5j6k7l8m9n0p1q2"
      DATABASE_URL: "mysql://root:azerty-26@database:3306/pitcrew?serverVersion=8.0&charset=utf8mb4"
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_DATABASE: pitcrew
      MYSQL_USER: root
      MYSQL_PASSWORD: azerty-26
      # Variables Stripe
      STRIPE_PUBLIC_KEY: "pk_test_example"
      STRIPE_SECRET_KEY: "sk_test_example"
      STRIPE_WEBHOOK_SECRET: "whsec_example"
      STRIPE_OFFLINE_MODE: "true"
      # Variables d'optimisation
      PHP_OPCACHE_ENABLE: 1
      PHP_OPCACHE_MEMORY_CONSUMPTION: 128
      PHP_OPCACHE_MAX_ACCELERATED_FILES: 4000
      PHP_OPCACHE_REVALIDATE_FREQ: 2
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - pitcrew_network
    links:
      - database:database
      - redis:redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - nginx-logs:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
    networks:
      - pitcrew_network
    restart: unless-stopped

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: azerty-26
      MYSQL_DATABASE: pitcrew
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pazerty-26"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - pitcrew_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - pitcrew_network
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - pitcrew_network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: azerty-26
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - pitcrew_network
    restart: unless-stopped

networks:
  pitcrew_network:
    driver: bridge

volumes:
  mysql-data:
  redis-data:
  symfony-cache:
  symfony-logs:
  nginx-logs:
  node-modules: 