version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      DATABASE_URL: "mysql://root:azerty-26@database:3306/blog?serverVersion=8.0"
    depends_on:
      - database

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: azerty-26
      MYSQL_DATABASE: blog
      MYSQL_USER: root
      MYSQL_PASSWORD: azerty-26
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33306:3306"

volumes:
  mysql-data: 