services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      DATABASE_URL: "mysql://root:azerty-26@database:3306/blog?serverVersion=8.0"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - pitcrew_network

  nginx:
    image: nginx:alpine
    ports:
      - "8888:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - pitcrew_network

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: azerty-26
      MYSQL_DATABASE: blog
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pazerty-26"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - pitcrew_network

networks:
  pitcrew_network:
    driver: bridge

volumes:
  mysql-data: 