framework:
    # Configuration intermédiaire entre dev et prod
    http_method_override: false
    handle_all_throwables: true
    
    # Cache optimisé pour la pré-production
    cache:
        app: cache.adapter.redis
        default_redis_provider: redis://redis:6379
    
    # Session optimisée
    session:
        handler_id: session.handler.redis
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    
    # Router optimisé
    router:
        cache_dir: '%kernel.cache_dir%/router'
        default_uri: null
    
    # Assets optimisés
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
        packages:
            app:
                json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
    
    # Profiler activé en pré-production pour le debugging
    profiler:
        enabled: true
        collect: true
    
    # Web profiler activé pour le debugging
    web_profiler:
        toolbar: true
        intercept_redirects: false 