<?php

declare(strict_types = 1);

/**
 * Preload file for OPcache optimization
 * This file is automatically generated by Symfony Flex.
 */

// Preload commonly used classes
require_once __DIR__ . '/../vendor/autoload.php';

// Preload Symfony core classes
require_once __DIR__ . '/../vendor/symfony/framework-bundle/Resources/config/annotations.php';
require_once __DIR__ . '/../vendor/symfony/framework-bundle/Resources/config/validator.php';

// Preload application classes
$classes = [
    // Controllers
    'App\Controller\SecurityController',
    'App\Controller\HomeController',
    'App\Controller\DashboardController',

    // Services
    'App\Service\MetricsCollector',
    'App\Service\RecommendationService',
    'App\Service\EmailValidationService',

    // Repositories
    'App\Repository\UserRepository',
    'App\Repository\PostRepository',

    // Entities
    'App\Entity\User',
    'App\Entity\Post',

    // Security
    'App\Security\LoginFormAuthenticator',
];

foreach ($classes as $class) {
    if (class_exists($class)) {
        // Force class loading
        new ReflectionClass($class);
    }
}
