parameters:
    cv_directory: '%kernel.project_dir%/public/uploads/cv'
    posts_directory: '%kernel.project_dir%/public/uploads/posts'
    post_images_directory: '%kernel.project_dir%/public/uploads/posts'
    resumes_directory: '%kernel.project_dir%/public/uploads/resumes'
    documents_directory: '%kernel.project_dir%/public/uploads/documents'
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    cover_letters_directory: '%kernel.project_dir%/public/uploads/cover_letters'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'
    stripe_webhook_secret: '%env(STRIPE_WEBHOOK_SECRET)%'
    stripe_offline_mode: '%env(bool:STRIPE_OFFLINE_MODE)%'
    logos_directory: '%kernel.project_dir%/public/uploads/logos'
    job_images_directory: '%kernel.project_dir%/public/uploads/job_images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        # Ces bindings ne sont plus nécessaires car ils sont maintenant accédés via ParameterBagInterface
        # Les commentaires ci-dessous sont conservés pour référence future
        # bind:
        #    $stripePublicKey: '%stripe_public_key%'
        #    $stripeSecretKey: '%stripe_secret_key%'
        #    $stripeWebhookSecret: '%stripe_webhook_secret%'
        #    $stripeOfflineMode: '%stripe_offline_mode%'
        #    $appEnv: '%env(APP_ENV)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # Le service FileUploader n'a plus besoin de configuration spéciale car il utilise ParameterBagInterface 

    App\Service\MetricsCollector:
        arguments:
            $logger: '@logger'

    App\Repository\PostRepository:
        arguments:
            $cache: '@cache.app'

    # Rendre le service de recommandation public pour les tests
    App\Service\RecommendationService:
        public: true 

    App\Service\EmailValidationService:
        arguments:
            $env: '%kernel.environment%'

    App\Validator\EmailValidator:
        arguments:
            $emailValidationService: '@App\Service\EmailValidationService'
        tags:
            - { name: validator.constraint_validator } 