name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Dependencies
      run: |
        composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        npm install
        
    - name: Build Assets
      run: npm run build
        
    - name: Create test database
      run: |
        mkdir -p var/data
        php bin/console --env=test doctrine:database:create
        php bin/console --env=test doctrine:schema:create
        
    - name: Execute tests
      env:
        DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data/blog_test.db"
      run: ./vendor/bin/phpunit --coverage-clover coverage.xml

  deploy:
    name: Deploy to Production
    needs: symfony-tests
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Install Production Dependencies
        run: |
          APP_ENV=prod composer install --no-dev --optimize-autoloader --no-interaction --no-progress --no-scripts
          APP_ENV=prod composer dump-env prod
        
      - name: Build assets
        run: |
          npm install
          npm run build
          
      - name: Deploy to production
        uses: deployphp/action@v1
        with:
          private-key: ${{secrets.DEPLOY_SSH_KEY}}
          deployer-version: "7.3.1"
          deployment: production
          dep: deploy 